### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by niko-lay** [uupaa/hlsdump#1]
```
$ node index.js --help
module.js:540
    throw err;
    ^

Error: Cannot find module './node_modules/uupaa.m3u8spooler.js/node_modules/uupaa.m3u8.js/node_modules/uupaa.uri.js/lib/URISearchParams.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at /home/niko/hls/hlsdump/index.js:40:1
    at Object.<anonymous> (/home/niko/hls/hlsdump/index.js:154:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

**Comment by tipoc123** [comment]
Open index.js and change these lines:
```
require("./node_modules/uupaa.m3u8spooler.js/node_modules/uupaa.m3u8.js/node_modules/uupaa.uri.js/lib/URISearchParams.js");
require("./node_modules/uupaa.m3u8spooler.js/node_modules/uupaa.m3u8.js/node_modules/uupaa.uri.js/lib/URI.js");
require("./node_modules/uupaa.mpeg2ts.js/node_modules/uupaa.fileloader.js/lib/FileLoader.js");
require("./node_modules/uupaa.mpeg2ts.js/node_modules/uupaa.fileloader.js/lib/FileLoaderQueue.js");
require("./node_modules/uupaa.m3u8spooler.js/node_modules/uupaa.m3u8.js/node_modules/uupaa.aacprofile.js/lib/AACProfile.js");
require("./node_modules/uupaa.m3u8spooler.js/node_modules/uupaa.m3u8.js/node_modules/uupaa.h264profile.js/lib/H264Profile.js");
require("./node_modules/uupaa.m3u8spooler.js/node_modules/uupaa.m3u8.js/lib/M3U8.js");
require("./node_modules/uupaa.nalunit.js/node_modules/uupaa.bit.js/lib/Bit.js");
require("./node_modules/uupaa.nalunit.js/node_modules/uupaa.bit.js/lib/BitView.js");
require("./node_modules/uupaa.aac.js/node_modules/uupaa.hash.js/lib/Hash.js");
require("./node_modules/uupaa.filestore.js/node_modules/uupaa.mimetype.js/lib/MimeType.js");
require("./node_modules/uupaa.mp4muxer.js/node_modules/uupaa.mp4parser.js/node_modules/uupaa.typedarray.js/lib/TypedArray.js");
require("./node_modules/uupaa.mp4muxer.js/node_modules/uupaa.mp4parser.js/lib/MP4Parser.js");
```
to next lines:
```
require("./node_modules/uupaa.uri.js/lib/URISearchParams.js");
require("./node_modules/uupaa.uri.js/lib/URI.js");
require("./node_modules/uupaa.fileloader.js/lib/FileLoader.js");
require("./node_modules/uupaa.fileloader.js/lib/FileLoaderQueue.js");
require("./node_modules/uupaa.aacprofile.js/lib/AACProfile.js");
require("./node_modules/uupaa.h264profile.js/lib/H264Profile.js");
require("./node_modules/uupaa.m3u8.js/lib/M3U8.js");
require("./node_modules/uupaa.bit.js/lib/Bit.js");
require("./node_modules/uupaa.bit.js/lib/BitView.js");
require("./node_modules/uupaa.hash.js/lib/Hash.js");
require("./node_modules/uupaa.mimetype.js/lib/MimeType.js");
require("./node_modules/uupaa.typedarray.js/lib/TypedArray.js");
require("./node_modules/uupaa.mp4parser.js/lib/MP4Parser.js");
```
